name: Build gitcg Minimal

# 只有手动触发
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # 最简化的检出步骤，没有任何额外选项
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cffi protobuf hatchling build wheel setuptools
    
    - name: Install Bun
      run: |
        powershell -c "irm bun.sh/install.ps1 | iex"
        echo "$HOME/.bun/bin" >> $GITHUB_PATH
      shell: bash
    
    - name: Verify Bun installation
      run: bun --version
      
    - name: Install project dependencies
      run: |
        bun install
      
    - name: Build JavaScript packages
      run: |
        bun run build
    
    - name: Create Python binding wheel
      run: |
        cd packages/pybinding
        python -m build --wheel
      env:
        PLATFORM_TAG: win_amd64
    
    - name: Upload Python binding wheel
      uses: actions/upload-artifact@v3
      with:
        name: gitcg-wheel
        path: packages/pybinding/dist/*.whl
        retention-days: 30
